# coding: utf-8

"""
    E-commerce Platform API

    API для управління замовленнями та оплатами в інтернет-магазині  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_get(self):
        """Test case for orders_get

        Отримати список замовлень  # noqa: E501
        """
        pass

    def test_orders_order_id_delete(self):
        """Test case for orders_order_id_delete

        Видалити замовлення  # noqa: E501
        """
        pass

    def test_orders_order_id_get(self):
        """Test case for orders_order_id_get

        Отримати замовлення за ID  # noqa: E501
        """
        pass

    def test_orders_order_id_put(self):
        """Test case for orders_order_id_put

        Оновити замовлення  # noqa: E501
        """
        pass

    def test_orders_post(self):
        """Test case for orders_post

        Створити нове замовлення  # noqa: E501
        """
        pass

    def test_payments_get(self):
        """Test case for payments_get

        Отримати список оплат  # noqa: E501
        """
        pass

    def test_payments_payment_id_delete(self):
        """Test case for payments_payment_id_delete

        Скасувати оплату  # noqa: E501
        """
        pass

    def test_payments_payment_id_get(self):
        """Test case for payments_payment_id_get

        Отримати оплату за ID  # noqa: E501
        """
        pass

    def test_payments_payment_id_put(self):
        """Test case for payments_payment_id_put

        Оновити оплату  # noqa: E501
        """
        pass

    def test_payments_post(self):
        """Test case for payments_post

        Зареєструвати оплату  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
