# coding: utf-8

# flake8: noqa

"""
    E-commerce Platform API

    API для управління замовленнями та оплатами в інтернет-магазині  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.order import Order
from swagger_client.models.payment import Payment
